import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { Router, type Request, type RequestHandler, type Response } from "express";
import rateLimit from "express-rate-limit";
import multer from "multer";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import {
  interviewStudioEvents,
  interviewStudioEvaluationJobs,
  interviewStudioResponses,
  interviewStudioSessions,
  interviewStudioTemplates,
} from "@shared/schema";
import {
  INTERVIEW_STUDIO_JAVASCRIPT_RUNTIME,
  canonicalizeInterviewStudioBlueprint,
  interviewStudioBlueprintSchema,
  sanitizeInterviewStudioItemForCandidate,
  sanitizeInterviewStudioTestRunForClient,
  summarizeInterviewStudioBlueprintForCatalog,
  type InterviewStudioBlueprint,
} from "@shared/interview-studio";
import { audit } from "../lib/audit";
import {
  isInterviewTranscriptionEnabled,
  transcribeInterviewAudio,
} from "../lib/interview-transcription";
import { logger } from "../lib/logger";
import {
  getInterviewStudioReadiness,
  interviewEventSchema,
  type InterviewEvent,
} from "../lib/interview-studio-policy";
import {
  isCodeRunnerEnabled,
  runInterviewCode,
} from "../lib/code-runner";
import {
  isInterviewAiEnabled,
} from "../lib/interview-ai";
import {
  enqueueInterviewStudioEvaluation,
  getInterviewStudioEvaluationWorkerConfig,
  InterviewStudioEvaluationQuotaError,
  InterviewStudioEvaluationWorkerUnavailableError,
} from "../lib/interview-studio-evaluation-worker";
import { deleteExpiredInterviewStudioPracticeSessions } from "../lib/interview-studio-retention-worker";
import { authenticateToken, type AuthenticatedRequest } from "../middleware/auth";
import { db } from "../db";

const router = Router();
const CONSENT_VERSION = "interview-practice-2026-07-16";
const PRACTICE_RETENTION_DAYS = 30;
const SUBMISSION_GRACE_MS = 15_000;
const EVALUATION_RETENTION_GRACE_MS = 24 * 60 * 60_000;
const MAX_RESPONSE_CHARACTERS = 20_000;
const MAX_SOURCE_BYTES = 50 * 1024;

/** Express 4 does not forward rejected async handlers to error middleware. */
const asyncHandler = (
  handler: (req: AuthenticatedRequest, res: Response) => Promise<unknown>,
): RequestHandler => (req, res, next) => {
  Promise.resolve(handler(req as AuthenticatedRequest, res)).catch(next);
};

const createSessionBodySchema = z.object({
  templateId: z.number().int().positive().optional(),
  templateKey: z.string().trim().min(3).max(120).optional(),
  mode: z.enum(["practice", "verified"]),
  consent: z.object({
    aiProcessing: z.boolean(),
    microphone: z.boolean(),
    camera: z.boolean(),
    screen: z.boolean(),
    consentVersion: z.string().trim().min(3).max(120),
  }).strict(),
}).strict().refine((value) => value.templateId != null || value.templateKey != null, {
  path: ["templateId"],
  message: "Choose an interview template",
});

const revealNextItemBodySchema = z.object({
  cursor: z.string().trim().min(20).max(2_000),
}).strict();

const responseBodySchema = z.object({
  responseText: z.string().max(MAX_RESPONSE_CHARACTERS).optional(),
  answerText: z.string().max(MAX_RESPONSE_CHARACTERS).optional(),
  code: z.string().optional(),
  language: z.literal("javascript").optional(),
  navigationCursor: z.string().trim().min(20).max(2_000),
  timeSpentSeconds: z.number().int().min(0).max(86_400).optional(),
}).strict().superRefine((value, context) => {
  const code = value.code ?? "";
  if (Buffer.byteLength(code, "utf8") > MAX_SOURCE_BYTES) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["code"], message: "Code cannot exceed 50 KB" });
  }
});

const startSessionBodySchema = z.object({
  permissions: z.object({
    camera: z.boolean(),
    microphone: z.boolean(),
    screen: z.boolean(),
  }).strict().optional(),
}).strict().default({});

const runSamplesBodySchema = z.object({
  itemKey: z.string().trim().min(3).max(120),
  code: z.string(),
  language: z.literal("javascript"),
  navigationCursor: z.string().trim().min(20).max(2_000),
}).strict().superRefine((value, context) => {
  if (!value.code.trim()) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["code"], message: "Add a solution before running tests" });
  }
  if (Buffer.byteLength(value.code, "utf8") > MAX_SOURCE_BYTES) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["code"], message: "Code cannot exceed 50 KB" });
  }
});

const eventEnvelopeFields = {
  idempotencyKey: z.string().trim().min(8).max(200).optional(),
  // Browser clocks are not authoritative. The persisted timestamp is always
  // generated by the server.
  occurredAt: z.string().datetime({ offset: true }).optional(),
  severity: z.enum(["info", "context", "warning"]).optional(),
};
const emptyEventMetadataSchema = z.object({}).strict().optional().default({});
const unavailableMetadataSchema = z.object({
  reason: z.enum(["permission_denied", "device_error"]),
  camera: z.boolean().optional(),
  microphone: z.boolean().optional(),
}).strict();

/**
 * A deliberately small browser-event allowlist. This endpoint cannot become a
 * generic device-fingerprinting or raw evidence channel.
 */
const browserEventBodySchema = z.discriminatedUnion("eventType", [
  z.object({ ...eventEnvelopeFields, eventType: z.literal("camera_microphone_ready"), metadata: z.object({
    camera: z.boolean(),
    microphone: z.boolean(),
  }).strict() }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("camera_microphone_unavailable"), metadata: unavailableMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("camera_permission_ended"), metadata: emptyEventMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("microphone_permission_ended"), metadata: emptyEventMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("screen_share_ready"), metadata: emptyEventMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("screen_share_ended"), metadata: emptyEventMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("screen_share_unavailable"), metadata: z.object({
    reason: z.enum(["permission_denied", "device_error"]),
  }).strict() }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("network_offline"), metadata: emptyEventMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("network_online"), metadata: emptyEventMetadataSchema }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("focus_left"), metadata: z.object({
    itemKey: z.string().trim().min(3).max(120).optional(),
  }).strict().optional().default({}) }).strict(),
  z.object({ ...eventEnvelopeFields, eventType: z.literal("focus_returned"), metadata: z.object({
    itemKey: z.string().trim().min(3).max(120).optional(),
  }).strict().optional().default({}) }).strict(),
]);

const writeLimiter = rateLimit({
  windowMs: 60_000,
  limit: 120,
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req) => `interview-user:${(req as AuthenticatedRequest).user?.userId ?? "unauthenticated"}`,
  message: { message: "Too many Interview Studio updates. Wait a moment and try again.", code: "INTERVIEW_RATE_LIMITED" },
});

const runnerLimiter = rateLimit({
  windowMs: 60 * 60_000,
  limit: 30,
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req) => `interview-runner:${(req as AuthenticatedRequest).user?.userId ?? "unauthenticated"}`,
  message: { message: "The sample-test limit has been reached for now.", code: "INTERVIEW_RUN_LIMITED" },
});

const audioLimiter = rateLimit({
  windowMs: 60 * 60_000,
  limit: 20,
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req) => `interview-audio:${(req as AuthenticatedRequest).user?.userId ?? "unauthenticated"}`,
  message: { message: "The voice-transcription limit has been reached for now.", code: "INTERVIEW_TRANSCRIPTION_RATE_LIMITED" },
});

function nowPlusDays(days: number) {
  return new Date(Date.now() + days * 86_400_000);
}

function sha256(value: string) {
  return crypto.createHash("sha256").update(value, "utf8").digest("hex");
}

function asBlueprint(value: unknown, expectedHash?: string) {
  const blueprint = interviewStudioBlueprintSchema.parse(value);
  if (expectedHash && sha256(canonicalizeInterviewStudioBlueprint(blueprint)) !== expectedHash) {
    throw Object.assign(new Error("Interview blueprint integrity check failed"), {
      code: "INTERVIEW_BLUEPRINT_INTEGRITY_FAILED",
      status: 500,
    });
  }
  return blueprint;
}

function findBlueprintItem(blueprint: InterviewStudioBlueprint, itemKey: string) {
  return blueprint.items.find((item) => item.key === itemKey);
}

function safeResponseText(body: z.infer<typeof responseBodySchema>) {
  return (body.responseText ?? body.answerText ?? "").trim();
}

function interviewReadiness() {
  const base = getInterviewStudioReadiness(process.env);
  const aiEvaluationEnabled = isInterviewAiEnabled(process.env);
  const codeRunnerEnabled = isCodeRunnerEnabled(process.env);
  const voiceTranscriptionEnabled = isInterviewTranscriptionEnabled(process.env);
  const evaluationWorkerEnabled = getInterviewStudioEvaluationWorkerConfig(process.env).enabled;
  return {
    practiceEnabled: base.practiceReady,
    // The data model already fails closed for verified evidence, but its
    // resumable private recording, human-review and expiring playback APIs are
    // intentionally not part of this private-practice release.
    verifiedEnabled: false,
    aiEvaluationEnabled,
    voiceTranscriptionEnabled,
    codeRunnerEnabled,
    recordingEnabled: false,
    evaluationWorkerEnabled,
    consentVersion: CONSENT_VERSION,
    limitations: [
      ...(!aiEvaluationEnabled ? ["ai_evaluation_not_configured"] : []),
      ...(!codeRunnerEnabled ? ["isolated_code_runner_not_configured"] : []),
      ...(!evaluationWorkerEnabled ? ["evaluation_worker_disabled"] : []),
      "verified_interview_workflow_not_released",
      "practice_sessions_are_private",
      "camera_and_screen_are_readiness_checks_only",
    ],
  };
}

async function loadOwnedSession(sessionId: string, userId: number) {
  const [session] = await db.select().from(interviewStudioSessions).where(and(
    eq(interviewStudioSessions.id, sessionId),
    eq(interviewStudioSessions.userId, userId),
  )).limit(1);
  return session;
}

type InterviewNavigationCursor = {
  sessionId: string;
  userId: number;
  currentIndex: number;
};

function navigationSecret(): string {
  const secret = process.env.JWT_SECRET;
  if (!secret) throw Object.assign(new Error("Interview navigation signing is unavailable"), { status: 503 });
  return secret;
}

function signNavigationCursor(value: InterviewNavigationCursor): string {
  const payload = Buffer.from(JSON.stringify(value), "utf8").toString("base64url");
  const signature = crypto.createHmac("sha256", navigationSecret()).update(payload).digest("base64url");
  return `${payload}.${signature}`;
}

function verifyNavigationCursor(raw: string): InterviewNavigationCursor | null {
  const [payload, signature, extra] = raw.split(".");
  if (!payload || !signature || extra) return null;
  const expected = crypto.createHmac("sha256", navigationSecret()).update(payload).digest();
  let received: Buffer;
  try {
    received = Buffer.from(signature, "base64url");
  } catch {
    return null;
  }
  if (received.length !== expected.length || !crypto.timingSafeEqual(received, expected)) return null;
  try {
    const parsed = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as Partial<InterviewNavigationCursor>;
    if (typeof parsed.sessionId !== "string" || !Number.isInteger(parsed.userId) || !Number.isInteger(parsed.currentIndex)) return null;
    return parsed as InterviewNavigationCursor;
  } catch {
    return null;
  }
}

function navigationCursorAllowsItem(input: {
  rawCursor: string;
  sessionId: string;
  userId: number;
  blueprint: InterviewStudioBlueprint;
  itemKey: string;
}): boolean {
  const cursor = verifyNavigationCursor(input.rawCursor);
  const itemIndex = input.blueprint.items.findIndex((item) => item.key === input.itemKey);
  return Boolean(
    cursor
    && cursor.sessionId === input.sessionId
    && cursor.userId === input.userId
    && itemIndex >= 0
    && itemIndex === cursor.currentIndex
    && cursor.currentIndex < input.blueprint.items.length,
  );
}

function candidateItemEvaluation(value: typeof interviewStudioResponses.$inferSelect.evaluation) {
  if (!value) return null;
  return {
    status: value.status,
    score: value.score,
    strengths: value.strengths,
    improvementAreas: value.improvementAreas,
    followUpQuestions: value.followUpQuestions,
    evaluatedAt: value.evaluatedAt,
  };
}

function candidateOverallEvaluation(value: typeof interviewStudioSessions.$inferSelect.evaluation) {
  if (!value) return null;
  return {
    status: value.status,
    score: value.score,
    competencyEvidence: value.competencyEvidence,
    summary: value.summary,
    strengths: value.strengths,
    improvementAreas: value.improvementAreas,
    humanReviewReasons: value.humanReviewReasons,
    evaluatedAt: value.evaluatedAt,
  };
}

async function sessionPayload(
  session: typeof interviewStudioSessions.$inferSelect,
  requestedCurrentIndex?: number,
) {
  const responses = await db.select().from(interviewStudioResponses)
    .where(eq(interviewStudioResponses.sessionId, session.id))
    .orderBy(interviewStudioResponses.id);
  const blueprint = asBlueprint(session.blueprintSnapshot, session.blueprintHash);
  const responseIndexes = responses
    .map((response) => blueprint.items.findIndex((item) => item.key === response.itemKey))
    .filter((index) => index >= 0);
  const derivedIndex = session.status === "in_progress"
    ? responseIndexes.length ? Math.max(...responseIndexes) : 0
    : responseIndexes.length
      ? Math.max(...responseIndexes)
      : -1;
  const currentIndex = requestedCurrentIndex == null
    ? derivedIndex
    : Math.max(-1, Math.min(requestedCurrentIndex, blueprint.items.length - 1));
  const active = session.status === "in_progress";
  const beforeDeadline = Boolean(session.serverDeadlineAt && Date.now() <= session.serverDeadlineAt.getTime());
  const currentItemKey = currentIndex >= 0 ? blueprint.items[currentIndex]?.key : undefined;
  const currentResponseSaved = Boolean(currentItemKey && responses.some((response) => response.itemKey === currentItemKey));
  const canRevealNext = active
    && beforeDeadline
    && currentResponseSaved
    && currentIndex >= 0
    && currentIndex < blueprint.items.length - 1;
  const visibleItems = currentIndex >= 0 && blueprint.items[currentIndex]
    ? [sanitizeInterviewStudioItemForCandidate(blueprint.items[currentIndex])]
    : [];
  return {
    id: session.id,
    templateId: session.templateId,
    templateKey: session.templateKey,
    templateVersion: session.templateVersion,
    mode: session.mode,
    status: session.status,
    blueprint: {
      title: blueprint.title,
      summary: blueprint.summary,
      role: blueprint.role,
      level: blueprint.level,
      skills: blueprint.skills,
      estimatedDurationMinutes: blueprint.estimatedDurationMinutes,
      itemCount: blueprint.items.length,
      codingCount: blueprint.items.filter((item) => item.kind === "coding").length,
      includesCoding: blueprint.items.some((item) => item.kind === "coding"),
      items: visibleItems,
    },
    navigation: {
      currentIndex: currentIndex >= 0 ? currentIndex : null,
      revealedCount: currentIndex >= 0 ? currentIndex + 1 : 0,
      totalItems: blueprint.items.length,
      canRevealNext,
      cursor: active && currentIndex >= 0
        ? signNavigationCursor({ sessionId: session.id, userId: session.userId, currentIndex })
        : null,
    },
    consent: session.consentSnapshot,
    permissions: session.permissionSnapshot,
    deadlineAt: session.serverDeadlineAt,
    serverNow: new Date().toISOString(),
    startedAt: session.startedAt,
    submittedAt: session.submittedAt,
    completedAt: session.completedAt,
    retentionUntil: session.retentionUntil,
    overallScore: session.overallScore,
    evaluationStatus: session.evaluationStatus,
    evaluation: candidateOverallEvaluation(session.evaluation),
    recruiterSharingEnabled: false,
    responses: responses.map((response) => {
      const publicSampleResult = response.sampleTestResult
        ? sanitizeInterviewStudioTestRunForClient(response.sampleTestResult)
        : null;
      if (publicSampleResult) delete (publicSampleResult as { hidden?: unknown }).hidden;
      return {
        itemKey: response.itemKey,
        itemKind: response.itemKind,
        responseText: response.answerText,
        answerText: response.answerText,
        code: response.code,
        language: response.language,
        timeSpentSeconds: response.timeSpentSeconds,
        sampleTestResult: publicSampleResult,
        evaluationStatus: response.evaluationStatus,
        evaluation: candidateItemEvaluation(response.evaluation),
        isFinal: response.isFinal,
        updatedAt: response.updatedAt,
      };
    }),
  };
}

async function appendSessionEvent(input: {
  sessionId: string;
  userId: number;
  type: InterviewEvent["type"];
  idempotencyKey?: string;
  payload?: unknown;
}) {
  const occurredAt = new Date();
  const event = interviewEventSchema.parse({
    idempotencyKey: input.idempotencyKey || `${input.type}:${occurredAt.toISOString()}:${crypto.randomUUID()}`,
    type: input.type,
    occurredAt: occurredAt.toISOString(),
    payload: input.payload || {},
  });
  await db.insert(interviewStudioEvents).values({
    sessionId: input.sessionId,
    userId: input.userId,
    idempotencyKey: event.idempotencyKey,
    type: event.type,
    payload: event.payload,
    occurredAt,
  }).onConflictDoNothing({
    target: [interviewStudioEvents.sessionId, interviewStudioEvents.idempotencyKey],
  });
}

router.get("/interview-studio/status", (_req, res) => {
  res.setHeader("Cache-Control", "private, no-store");
  res.json(interviewReadiness());
});

router.get("/interview-studio/templates", authenticateToken, asyncHandler(async (_req, res) => {
  const readiness = interviewReadiness();
  if (!readiness.practiceEnabled) {
    return res.status(503).json({ message: "Interview Studio is not enabled in this environment", code: "INTERVIEW_STUDIO_DISABLED" });
  }
  const templates = await db.select().from(interviewStudioTemplates).where(and(
    eq(interviewStudioTemplates.state, "published"),
    eq(interviewStudioTemplates.isCurrent, true),
  )).orderBy(interviewStudioTemplates.title);
  const items = templates.map((template) => {
    const blueprint = asBlueprint(template.blueprint, template.blueprintHash);
    const supportedModes = [...template.supportedModes].sort();
    const allowedModes = [...blueprint.allowedModes].sort();
    if (JSON.stringify(supportedModes) !== JSON.stringify(allowedModes)) {
      throw Object.assign(new Error("Interview template mode snapshot is inconsistent"), { status: 500 });
    }
    return {
      id: template.id,
      key: template.templateKey,
      templateKey: template.templateKey,
      version: template.version,
      title: template.title,
      targetRole: blueprint.role,
      description: template.summary,
      summary: template.summary,
      skills: blueprint.skills,
      difficulty: blueprint.level,
      durationMinutes: blueprint.estimatedDurationMinutes,
      availableModes: template.supportedModes.filter((mode) => mode === "practice" || readiness.verifiedEnabled),
      ...summarizeInterviewStudioBlueprintForCatalog(blueprint),
    };
  });
  res.setHeader("Cache-Control", "private, no-store");
  res.json({ items });
}));

router.get("/interview-studio/sessions", authenticateToken, asyncHandler(async (req, res) => {
  const sessions = await db.select({
    id: interviewStudioSessions.id,
    templateKey: interviewStudioSessions.templateKey,
    templateVersion: interviewStudioSessions.templateVersion,
    mode: interviewStudioSessions.mode,
    status: interviewStudioSessions.status,
    overallScore: interviewStudioSessions.overallScore,
    evaluationStatus: interviewStudioSessions.evaluationStatus,
    startedAt: interviewStudioSessions.startedAt,
    completedAt: interviewStudioSessions.completedAt,
    retentionUntil: interviewStudioSessions.retentionUntil,
    createdAt: interviewStudioSessions.createdAt,
  }).from(interviewStudioSessions)
    .where(eq(interviewStudioSessions.userId, req.user!.userId))
    .orderBy(desc(interviewStudioSessions.createdAt))
    .limit(50);
  res.setHeader("Cache-Control", "private, no-store");
  res.json({ items: sessions });
}));

router.post("/interview-studio/sessions", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const parsed = createSessionBodySchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ message: "Review the interview setup and consent choices", errors: parsed.error.flatten() });
  }
  const readiness = interviewReadiness();
  if (!readiness.practiceEnabled) {
    return res.status(503).json({ message: "Interview Studio is not enabled", code: "INTERVIEW_STUDIO_DISABLED" });
  }
  if (parsed.data.mode === "verified" && !readiness.verifiedEnabled) {
    return res.status(409).json({
      message: "Verified interviews are not open yet. Private practice is available now.",
      code: "VERIFIED_INTERVIEW_NOT_READY",
    });
  }
  if (parsed.data.consent.consentVersion !== CONSENT_VERSION) {
    return res.status(409).json({ message: "The interview disclosure has changed. Review it again before starting.", code: "INTERVIEW_CONSENT_OUTDATED" });
  }
  const templateCondition = parsed.data.templateId
    ? eq(interviewStudioTemplates.id, parsed.data.templateId)
    : eq(interviewStudioTemplates.templateKey, parsed.data.templateKey!);
  const [template] = await db.select().from(interviewStudioTemplates).where(and(
    templateCondition,
    eq(interviewStudioTemplates.state, "published"),
    eq(interviewStudioTemplates.isCurrent, true),
  )).limit(1);
  if (!template) return res.status(404).json({ message: "Interview template not found" });
  if (!template.supportedModes.includes(parsed.data.mode)) {
    return res.status(409).json({ message: "This template does not support the selected interview mode" });
  }

  const blueprint = asBlueprint(template.blueprint, template.blueprintHash);
  const now = new Date();
  const sessionId = crypto.randomUUID();
  const [session] = await db.insert(interviewStudioSessions).values({
    id: sessionId,
    templateId: template.id,
    templateKey: template.templateKey,
    templateVersion: template.version,
    userId: req.user!.userId,
    mode: parsed.data.mode,
    status: "ready",
    blueprintSnapshot: blueprint,
    blueprintHash: template.blueprintHash,
    consentSnapshot: {
      policyVersion: CONSENT_VERSION,
      acknowledgedAt: now.toISOString(),
      aiEvaluation: parsed.data.consent.aiProcessing,
      microphoneTranscription: parsed.data.consent.microphone,
      // Practice camera/screen are local readiness checks, never recordings.
      cameraRecording: false,
      screenRecording: false,
      recruiterSharing: false,
    },
    permissionSnapshot: {
      capturedAt: now.toISOString(),
      camera: { required: parsed.data.consent.camera, state: "not_requested" },
      microphone: { required: parsed.data.consent.microphone, state: "not_requested" },
      screen: { required: parsed.data.consent.screen, state: "not_requested" },
    },
    serverDeadlineAt: null,
    evaluationStatus: parsed.data.consent.aiProcessing ? "pending" : "not_requested",
    retentionUntil: nowPlusDays(PRACTICE_RETENTION_DAYS),
  }).returning();

  await audit({
    action: "interview_studio.session_created",
    userId: req.user!.userId,
    actorRole: "learner",
    resourceType: "interview_studio_session",
    resourceId: session.id,
    metadata: {
      templateKey: template.templateKey,
      templateVersion: template.version,
      mode: parsed.data.mode,
      aiEvaluationConsent: parsed.data.consent.aiProcessing,
      microphoneTranscriptionConsent: parsed.data.consent.microphone,
    },
    req,
  });
  res.status(201).json(await sessionPayload(session));
}));

router.get("/interview-studio/sessions/:sessionId", authenticateToken, asyncHandler(async (req, res) => {
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  res.setHeader("Cache-Control", "private, no-store");
  res.json(await sessionPayload(session));
}));

router.post("/interview-studio/sessions/:sessionId/start", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const parsedBody = startSessionBodySchema.safeParse(req.body || {});
  if (!parsedBody.success) return res.status(400).json({ message: "Invalid device-readiness state" });
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (session.status === "in_progress") return res.json(await sessionPayload(session));
  if (session.status !== "ready") {
    return res.status(409).json({ message: "This interview can no longer be started", code: "INTERVIEW_INVALID_STATE" });
  }
  const blueprint = asBlueprint(session.blueprintSnapshot, session.blueprintHash);
  const startedAt = new Date();
  const serverDeadlineAt = new Date(startedAt.getTime() + blueprint.estimatedDurationMinutes * 60_000);
  if (session.retentionUntil.getTime() <= serverDeadlineAt.getTime() + EVALUATION_RETENTION_GRACE_MS) {
    await db.update(interviewStudioSessions).set({
      status: "expired",
      updatedAt: startedAt,
    }).where(and(
      eq(interviewStudioSessions.id, session.id),
      eq(interviewStudioSessions.userId, req.user!.userId),
      eq(interviewStudioSessions.status, "ready"),
    ));
    return res.status(410).json({
      message: "This saved setup is too old to complete safely. Create a new private practice session.",
      code: "INTERVIEW_SESSION_EXPIRED",
    });
  }
  const permissions = parsedBody.data.permissions;
  const [started] = await db.update(interviewStudioSessions).set({
    status: "in_progress",
    startedAt,
    serverDeadlineAt,
    permissionSnapshot: {
      capturedAt: startedAt.toISOString(),
      camera: {
        required: session.permissionSnapshot.camera.required,
        state: permissions?.camera ? "granted" : "not_requested",
      },
      microphone: {
        required: session.permissionSnapshot.microphone.required,
        state: permissions?.microphone ? "granted" : "not_requested",
      },
      screen: {
        required: session.permissionSnapshot.screen.required,
        state: permissions?.screen ? "granted" : "not_requested",
      },
    },
    updatedAt: startedAt,
  }).where(and(
    eq(interviewStudioSessions.id, session.id),
    eq(interviewStudioSessions.userId, req.user!.userId),
    eq(interviewStudioSessions.status, "ready"),
  )).returning();
  if (!started) {
    const concurrent = await loadOwnedSession(session.id, req.user!.userId);
    if (concurrent?.status === "in_progress") return res.json(await sessionPayload(concurrent));
    return res.status(409).json({ message: "This interview could not be started" });
  }
  await appendSessionEvent({ sessionId: session.id, userId: req.user!.userId, type: "session_started" });
  res.json(await sessionPayload(started, 0));
}));

router.post("/interview-studio/sessions/:sessionId/items/next", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const parsed = revealNextItemBodySchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: "A valid interview navigation cursor is required" });
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (session.status !== "in_progress") {
    return res.status(409).json({ message: "This interview is not accepting navigation changes", code: "INTERVIEW_INVALID_STATE" });
  }
  if (!session.serverDeadlineAt || Date.now() > session.serverDeadlineAt.getTime()) {
    return res.status(409).json({ message: "The interview timer has ended. Submit your saved responses.", code: "INTERVIEW_DEADLINE_PASSED" });
  }
  const cursor = verifyNavigationCursor(parsed.data.cursor);
  if (!cursor
    || cursor.sessionId !== session.id
    || cursor.userId !== req.user!.userId
    || cursor.currentIndex < 0) {
    return res.status(409).json({ message: "Refresh this interview before continuing", code: "INTERVIEW_NAVIGATION_STALE" });
  }
  const blueprint = asBlueprint(session.blueprintSnapshot, session.blueprintHash);
  if (cursor.currentIndex >= blueprint.items.length - 1) {
    return res.status(409).json({ message: "There are no more interview prompts", code: "INTERVIEW_NO_NEXT_ITEM" });
  }
  const currentItem = blueprint.items[cursor.currentIndex];
  const [savedCurrentResponse] = await db.select({ id: interviewStudioResponses.id })
    .from(interviewStudioResponses)
    .where(and(
      eq(interviewStudioResponses.sessionId, session.id),
      eq(interviewStudioResponses.itemKey, currentItem.key),
    ))
    .limit(1);
  if (!savedCurrentResponse) {
    return res.status(409).json({
      message: "Save a response to the current prompt before opening the next one",
      code: "INTERVIEW_CURRENT_RESPONSE_REQUIRED",
    });
  }
  res.setHeader("Cache-Control", "private, no-store");
  res.json(await sessionPayload(session, cursor.currentIndex + 1));
}));

router.put("/interview-studio/sessions/:sessionId/responses/:itemKey", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const parsed = responseBodySchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: "Check this response", errors: parsed.error.flatten() });
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (session.status !== "in_progress") return res.status(409).json({ message: "This interview is not accepting responses" });
  if (!session.serverDeadlineAt || Date.now() > session.serverDeadlineAt.getTime() + SUBMISSION_GRACE_MS) {
    return res.status(409).json({ message: "The interview timer has ended. Submit your saved responses.", code: "INTERVIEW_DEADLINE_PASSED" });
  }
  const blueprint = asBlueprint(session.blueprintSnapshot, session.blueprintHash);
  const item = findBlueprintItem(blueprint, req.params.itemKey);
  if (!item) return res.status(404).json({ message: "Interview item not found" });
  if (!navigationCursorAllowsItem({
    rawCursor: parsed.data.navigationCursor,
    sessionId: session.id,
    userId: req.user!.userId,
    blueprint,
    itemKey: item.key,
  })) {
    return res.status(409).json({ message: "Open this prompt through the interview navigator before responding", code: "INTERVIEW_ITEM_NOT_REVEALED" });
  }

  const answerText = safeResponseText(parsed.data);
  const code = parsed.data.code?.trim() || "";
  if (item.kind === "structured_response" && !answerText) {
    return res.json({ saved: false, reason: "empty_response", serverNow: new Date().toISOString() });
  }
  if (item.kind === "coding" && !code) {
    return res.json({ saved: false, reason: "empty_response", serverNow: new Date().toISOString() });
  }
  if (item.kind === "structured_response" && code) return res.status(400).json({ message: "Code cannot be saved for this response" });
  if (item.kind === "coding" && parsed.data.language !== "javascript") return res.status(400).json({ message: "This challenge uses JavaScript" });
  if (item.kind === "structured_response") {
    const words = answerText.match(/\S+/g)?.length || 0;
    if (words > item.maximumWords) {
      return res.status(422).json({
        message: `Keep this response within ${item.maximumWords} words. Your browser draft has not been discarded.`,
        code: "INTERVIEW_RESPONSE_WORD_LIMIT",
      });
    }
  }

  const now = new Date();
  const content = item.kind === "coding" ? code : answerText;
  const [saved] = await db.insert(interviewStudioResponses).values({
    sessionId: session.id,
    itemKey: item.key,
    itemKind: item.kind,
    answerText: item.kind === "structured_response" ? answerText : null,
    code: item.kind === "coding" ? code : null,
    language: item.kind === "coding" ? "javascript" : null,
    timeSpentSeconds: parsed.data.timeSpentSeconds ?? 0,
    answerHash: sha256(content),
    evaluationStatus: session.consentSnapshot.aiEvaluation ? "pending" : "not_requested",
    updatedAt: now,
  }).onConflictDoUpdate({
    target: [interviewStudioResponses.sessionId, interviewStudioResponses.itemKey],
    set: {
      answerText: item.kind === "structured_response" ? answerText : null,
      code: item.kind === "coding" ? code : null,
      language: item.kind === "coding" ? "javascript" : null,
      ...(parsed.data.timeSpentSeconds !== undefined
        ? { timeSpentSeconds: parsed.data.timeSpentSeconds }
        : {}),
      answerHash: sha256(content),
      evaluationStatus: session.consentSnapshot.aiEvaluation ? "pending" : "not_requested",
      updatedAt: now,
    },
  }).returning();
  res.json({ saved: true, response: saved, serverNow: now.toISOString() });
}));

router.post("/interview-studio/sessions/:sessionId/events", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const parsed = browserEventBodySchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: "Invalid interview event" });
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (!["ready", "in_progress"].includes(session.status)) {
    return res.status(409).json({ message: "This interview is no longer accepting browser events" });
  }

  const append = (type: InterviewEvent["type"], payload: unknown = {}) => appendSessionEvent({
    sessionId: session.id,
    userId: req.user!.userId,
    type,
    idempotencyKey: parsed.data.idempotencyKey
      ? `browser:${sha256(`${parsed.data.idempotencyKey}:${type}:${JSON.stringify(payload)}`).slice(0, 48)}`
      : undefined,
    payload,
  });
  const stateFromReason = (reason: "permission_denied" | "device_error") => (
    reason === "permission_denied" ? "denied" : "unavailable"
  );

  switch (parsed.data.eventType) {
    case "camera_microphone_ready":
      if (parsed.data.metadata.camera) await append("permission_changed", { device: "camera", state: "granted" });
      if (parsed.data.metadata.microphone) await append("permission_changed", { device: "microphone", state: "granted" });
      break;
    case "camera_microphone_unavailable": {
      const state = stateFromReason(parsed.data.metadata.reason);
      if (parsed.data.metadata.camera !== false) await append("permission_changed", { device: "camera", state });
      if (parsed.data.metadata.microphone !== false) await append("permission_changed", { device: "microphone", state });
      break;
    }
    case "camera_permission_ended":
      await append("permission_changed", { device: "camera", state: "unavailable" });
      break;
    case "microphone_permission_ended":
      await append("permission_changed", { device: "microphone", state: "unavailable" });
      break;
    case "screen_share_ready":
      await append("permission_changed", { device: "screen", state: "granted" });
      break;
    case "screen_share_unavailable":
      await append("permission_changed", { device: "screen", state: stateFromReason(parsed.data.metadata.reason) });
      break;
    case "screen_share_ended":
      await append("screen_share_ended");
      break;
    case "network_offline":
      await append("network_offline");
      break;
    case "network_online":
      await append("network_online");
      break;
    case "focus_left":
      await append("focus_left", parsed.data.metadata.itemKey ? { itemKey: parsed.data.metadata.itemKey } : {});
      break;
    case "focus_returned":
      await append("focus_returned", parsed.data.metadata.itemKey ? { itemKey: parsed.data.metadata.itemKey } : {});
      break;
  }
  res.status(202).json({ accepted: true });
}));

router.post("/interview-studio/sessions/:sessionId/run-samples", authenticateToken, runnerLimiter, asyncHandler(async (req, res) => {
  const parsed = runSamplesBodySchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: "Check the code submission", errors: parsed.error.flatten() });
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (session.status !== "in_progress") return res.status(409).json({ message: "This interview is not accepting test runs" });
  if (!session.serverDeadlineAt || Date.now() > session.serverDeadlineAt.getTime() + SUBMISSION_GRACE_MS) {
    return res.status(409).json({ message: "The interview timer has ended. Submit your saved code.", code: "INTERVIEW_DEADLINE_PASSED" });
  }
  const blueprint = asBlueprint(session.blueprintSnapshot, session.blueprintHash);
  const item = findBlueprintItem(blueprint, parsed.data.itemKey);
  if (!item || item.kind !== "coding") return res.status(404).json({ message: "Coding challenge not found" });
  if (!navigationCursorAllowsItem({
    rawCursor: parsed.data.navigationCursor,
    sessionId: session.id,
    userId: req.user!.userId,
    blueprint,
    itemKey: item.key,
  })) {
    return res.status(409).json({ message: "Open this challenge through the interview navigator before running it", code: "INTERVIEW_ITEM_NOT_REVEALED" });
  }
  if (!isCodeRunnerEnabled(process.env)) {
    return res.status(503).json({ message: "The isolated code runner is not configured yet. Your code can still be saved.", code: "CODE_RUNNER_DISABLED" });
  }
  try {
    const result = await runInterviewCode({ sourceCode: parsed.data.code, item, scope: "public" });
    const currentSession = await loadOwnedSession(session.id, req.user!.userId);
    if (!currentSession || currentSession.status !== "in_progress"
      || !currentSession.serverDeadlineAt
      || Date.now() > currentSession.serverDeadlineAt.getTime() + SUBMISSION_GRACE_MS) {
      return res.status(409).json({
        message: "The interview closed while the sample tests were running. The previously saved code is unchanged.",
        code: "INTERVIEW_RUN_FINISHED_AFTER_CLOSE",
      });
    }
    const now = new Date();
    const [saved] = await db.insert(interviewStudioResponses).values({
      sessionId: session.id,
      itemKey: item.key,
      itemKind: "coding",
      code: parsed.data.code,
      language: "javascript",
      answerHash: sha256(parsed.data.code),
      sampleTestResult: result,
      evaluationStatus: "pending",
      updatedAt: now,
    }).onConflictDoUpdate({
      target: [interviewStudioResponses.sessionId, interviewStudioResponses.itemKey],
      set: {
        code: parsed.data.code,
        language: "javascript",
        answerHash: sha256(parsed.data.code),
        sampleTestResult: result,
        updatedAt: now,
      },
    }).returning();
    await appendSessionEvent({
      sessionId: session.id,
      userId: req.user!.userId,
      type: "tests_requested",
      payload: { itemKey: item.key, scope: "public" },
    });
    const clientResult = sanitizeInterviewStudioTestRunForClient(result);
    delete (clientResult as { hidden?: unknown }).hidden;
    res.json({ ...clientResult, result: clientResult, responseId: saved.id });
  } catch (error) {
    logger.warn("interview_studio.sample_run_failed", { sessionId: session.id, userId: req.user!.userId, error });
    const status = Number((error as { status?: number }).status) || 502;
    res.status(status).json({ message: error instanceof Error ? error.message : "The sample tests could not run", code: "CODE_RUN_FAILED" });
  }
}));

router.post("/interview-studio/sessions/:sessionId/submit", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (["completed", "review_required"].includes(session.status)) return res.json(await sessionPayload(session));
  if (session.status === "evaluating") return res.status(202).json({ status: "evaluating", message: "Your practice feedback is still being prepared." });
  if (session.status !== "in_progress") return res.status(409).json({ message: "This interview cannot be submitted" });
  let queued;
  try {
    queued = await enqueueInterviewStudioEvaluation({
      sessionId: session.id,
      userId: req.user!.userId,
    });
  } catch (error) {
    if (error instanceof InterviewStudioEvaluationQuotaError) {
      return res.status(error.status).json({
        message: error.message,
        code: error.code,
        dailyLimit: error.limit,
      });
    }
    if (error instanceof InterviewStudioEvaluationWorkerUnavailableError) {
      return res.status(error.status).json({ message: error.message, code: error.code });
    }
    throw error;
  }
  if (queued.state === "already_finished") {
    const finished = await loadOwnedSession(session.id, req.user!.userId);
    return finished ? res.json(await sessionPayload(finished)) : res.status(404).json({ message: "Interview session not found" });
  }
  if (queued.state === "already_evaluating") {
    return res.status(202).json({ status: "evaluating", message: "Your practice feedback is still being prepared." });
  }
  if (queued.state !== "queued") {
    return res.status(409).json({ message: "This interview cannot be submitted", code: "INTERVIEW_SUBMISSION_STATE_CHANGED" });
  }
  await audit({
    action: "interview_studio.session_submitted",
    userId: req.user!.userId,
    actorRole: "learner",
    resourceType: "interview_studio_session",
    resourceId: queued.session.id,
    metadata: {
      mode: queued.session.mode,
      evaluationStatus: "pending",
      evaluationJobId: queued.jobId,
      dailyEvaluationUsed: queued.dailyUsed,
      dailyEvaluationLimit: queued.dailyLimit,
      aiEvaluationAllowed: queued.aiEvaluationAllowed,
      dailyRunnerUsed: queued.runnerDailyUsed,
      dailyRunnerLimit: queued.runnerDailyLimit,
      codeRunnerAllowed: queued.codeRunnerAllowed,
    },
    req,
  });
  return res.status(202).json({
    status: "evaluating",
    evaluationStatus: "pending",
    message: "Your responses are saved. Practice feedback is being prepared.",
  });
}));

const AUDIO_DIR = path.join(os.tmpdir(), "octamy-interview-audio");
fs.mkdirSync(AUDIO_DIR, { recursive: true, mode: 0o700 });
const AUDIO_MIME_TYPES = new Set([
  "audio/webm",
  "audio/mp4",
  "audio/mpeg",
  "audio/wav",
  "audio/x-wav",
]);
const audioUpload = multer({
  storage: multer.diskStorage({
    destination: (_req, _file, callback) => callback(null, AUDIO_DIR),
    filename: (_req, file, callback) => {
      const extension = file.mimetype.includes("webm")
        ? ".webm"
        : file.mimetype === "audio/mp4"
          ? ".m4a"
          : file.mimetype === "audio/mpeg"
            ? ".mp3"
            : ".wav";
      callback(null, `voice-${crypto.randomUUID()}${extension}`);
    },
  }),
  limits: { fileSize: 15 * 1024 * 1024, files: 1 },
  fileFilter: (_req, file, callback) => {
    if (!AUDIO_MIME_TYPES.has(file.mimetype)) return callback(new Error("Unsupported audio format"));
    callback(null, true);
  },
});

function audioSignatureMatches(filePath: string, mimeType: string) {
  const descriptor = fs.openSync(filePath, "r");
  const header = Buffer.alloc(16);
  try {
    fs.readSync(descriptor, header, 0, header.length, 0);
  } finally {
    fs.closeSync(descriptor);
  }
  if (mimeType === "audio/webm") {
    if (!header.subarray(0, 4).equals(Buffer.from([0x1a, 0x45, 0xdf, 0xa3]))) return false;
    // MediaRecorder emits TrackType as 83 81 02 for audio and 83 81 01 for
    // video. Inspect bounded container metadata so a custom client cannot send
    // camera footage through the transient voice endpoint.
    const metadata = readFilePrefix(filePath, 1024 * 1024);
    const hasAudioTrack = metadata.indexOf(Buffer.from([0x83, 0x81, 0x02])) >= 0;
    const hasVideoTrack = metadata.indexOf(Buffer.from([0x83, 0x81, 0x01])) >= 0
      || /V_(?:VP8|VP9|AV1|MPEG)/.test(metadata.toString("latin1"));
    return hasAudioTrack && !hasVideoTrack;
  }
  if (mimeType === "audio/mp4") {
    if (header.subarray(4, 8).toString() !== "ftyp") return false;
    const metadata = Buffer.concat([
      readFilePrefix(filePath, 1024 * 1024),
      readFileTail(filePath, 1024 * 1024),
    ]).toString("latin1");
    return metadata.includes("soun") && !metadata.includes("vide");
  }
  if (mimeType === "audio/wav" || mimeType === "audio/x-wav") {
    return header.subarray(0, 4).toString() === "RIFF" && header.subarray(8, 12).toString() === "WAVE";
  }
  if (mimeType === "audio/mpeg") {
    return header.subarray(0, 3).toString() === "ID3" || (header[0] === 0xff && (header[1] & 0xe0) === 0xe0);
  }
  return false;
}

function readFilePrefix(filePath: string, maximumBytes: number) {
  const descriptor = fs.openSync(filePath, "r");
  try {
    const size = Math.min(fs.fstatSync(descriptor).size, maximumBytes);
    const buffer = Buffer.alloc(size);
    const bytesRead = fs.readSync(descriptor, buffer, 0, size, 0);
    return buffer.subarray(0, bytesRead);
  } finally {
    fs.closeSync(descriptor);
  }
}

function readFileTail(filePath: string, maximumBytes: number) {
  const descriptor = fs.openSync(filePath, "r");
  try {
    const fileSize = fs.fstatSync(descriptor).size;
    const size = Math.min(fileSize, maximumBytes);
    const buffer = Buffer.alloc(size);
    const bytesRead = fs.readSync(descriptor, buffer, 0, size, Math.max(0, fileSize - size));
    return buffer.subarray(0, bytesRead);
  } finally {
    fs.closeSync(descriptor);
  }
}

async function cleanupStaleTransientAudio() {
  const staleBefore = Date.now() - 60 * 60_000;
  const entries = await fs.promises.readdir(AUDIO_DIR, { withFileTypes: true });
  await Promise.all(entries.map(async (entry) => {
    if (!entry.isFile() || !/^voice-[0-9a-f-]+\.(?:webm|m4a|mp3|wav)$/.test(entry.name)) return;
    const filePath = path.join(AUDIO_DIR, entry.name);
    const stat = await fs.promises.stat(filePath);
    if (stat.mtimeMs < staleBefore) await fs.promises.unlink(filePath).catch(() => undefined);
  }));
}

void cleanupStaleTransientAudio().catch((error) => {
  logger.warn("interview_studio.transient_audio_cleanup_failed", { error });
});

router.post(
  "/interview-studio/sessions/:sessionId/transcribe/:itemKey",
  authenticateToken,
  audioLimiter,
  (req: AuthenticatedRequest, res: Response) => {
    audioUpload.single("audio")(req as Request, res, async (uploadError) => {
      if (uploadError) {
        const status = uploadError instanceof multer.MulterError && uploadError.code === "LIMIT_FILE_SIZE" ? 413 : 400;
        return res.status(status).json({ message: uploadError.message, code: "INTERVIEW_AUDIO_INVALID" });
      }
      const file = req.file;
      if (!file) return res.status(400).json({ message: "Record a voice response first" });
      try {
        const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
        if (!session) return res.status(404).json({ message: "Interview session not found" });
        if (session.status !== "in_progress") return res.status(409).json({ message: "This interview is not accepting voice responses" });
        if (!session.consentSnapshot.microphoneTranscription || !session.consentSnapshot.aiEvaluation) {
          return res.status(403).json({ message: "Voice transcription requires the microphone and AI-processing choices shown before the interview" });
        }
        const blueprint = asBlueprint(session.blueprintSnapshot, session.blueprintHash);
        const item = findBlueprintItem(blueprint, req.params.itemKey);
        if (!item || item.kind !== "structured_response") return res.status(404).json({ message: "Structured interview prompt not found" });
        const navigationCursor = typeof req.body?.navigationCursor === "string" ? req.body.navigationCursor : "";
        if (!navigationCursorAllowsItem({
          rawCursor: navigationCursor,
          sessionId: session.id,
          userId: req.user!.userId,
          blueprint,
          itemKey: item.key,
        })) {
          return res.status(409).json({ message: "Open this prompt through the interview navigator before transcribing", code: "INTERVIEW_ITEM_NOT_REVEALED" });
        }
        if (!audioSignatureMatches(file.path, file.mimetype)) {
          return res.status(400).json({ message: "The recorded file did not match its audio format" });
        }
        const result = await transcribeInterviewAudio(file.path);
        await audit({
          action: "interview_studio.voice_transcribed",
          userId: req.user!.userId,
          actorRole: "learner",
          resourceType: "interview_studio_session",
          resourceId: session.id,
          metadata: { itemKey: item.key, model: result.model, rawAudioRetained: false },
          req,
        });
        res.json({ text: result.text, model: result.model, rawAudioRetained: false });
      } catch (error) {
        logger.warn("interview_studio.transcription_failed", { sessionId: req.params.sessionId, userId: req.user!.userId, error });
        const status = Number((error as { status?: number }).status) || 502;
        res.status(status).json({
          message: status === 503 ? "Voice transcription is not configured yet. Type your response instead." : "This voice response could not be transcribed. Type or record it again.",
          code: (error as { code?: string }).code || "INTERVIEW_TRANSCRIPTION_FAILED",
        });
      } finally {
        await fs.promises.unlink(file.path).catch(() => undefined);
      }
    });
  },
);

router.delete("/interview-studio/sessions/:sessionId", authenticateToken, writeLimiter, asyncHandler(async (req, res) => {
  const session = await loadOwnedSession(req.params.sessionId, req.user!.userId);
  if (!session) return res.status(404).json({ message: "Interview session not found" });
  if (session.mode !== "practice" || session.recruiterSharingEnabled) {
    return res.status(409).json({ message: "Shared verified evidence must be revoked before deletion" });
  }
  if (session.status === "evaluating") {
    await db.update(interviewStudioSessions).set({
      status: "cancelled",
      updatedAt: new Date(),
    }).where(and(
      eq(interviewStudioSessions.id, session.id),
      eq(interviewStudioSessions.userId, req.user!.userId),
      eq(interviewStudioSessions.status, "evaluating"),
    ));
    const [runningJob] = await db.select({ id: interviewStudioEvaluationJobs.id })
      .from(interviewStudioEvaluationJobs)
      .where(and(
        eq(interviewStudioEvaluationJobs.sessionId, session.id),
        eq(interviewStudioEvaluationJobs.status, "running"),
      )).limit(1);
    if (runningJob) {
      await audit({
        action: "interview_studio.session_deletion_requested",
        userId: req.user!.userId,
        actorRole: "learner",
        resourceType: "interview_studio_session",
        resourceId: session.id,
        metadata: { mode: session.mode, evaluationCancellationRequested: true },
        req,
      });
      return res.status(202).json({ deleted: false, deletionPending: true });
    }
  }
  await db.delete(interviewStudioSessions).where(and(
    eq(interviewStudioSessions.id, session.id),
    eq(interviewStudioSessions.userId, req.user!.userId),
  ));
  await audit({
    action: "interview_studio.session_deleted",
    userId: req.user!.userId,
    actorRole: "learner",
    resourceType: "interview_studio_session",
    resourceId: session.id,
    metadata: { mode: session.mode },
    req,
  });
  res.status(204).end();
}));

// Opportunistic retention cleanup. A database/queue scheduled job should call
// the same deletion rule in production; this keeps expired private practice
// data from surviving indefinitely even in a single-process deployment.
router.post("/interview-studio/maintenance/retention", authenticateToken, asyncHandler(async (req, res) => {
  if (!req.user?.isAdmin) return res.status(403).json({ message: "Admin access required" });
  const cleanup = await deleteExpiredInterviewStudioPracticeSessions(1_000);
  res.json(cleanup);
}));

export default router;
