#!/usr/bin/env tsx

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

type Difficulty = "easy" | "medium" | "hard";

type Draft = {
  topic: string;
  topicSlug: string;
  objectiveCode: string;
  objective: string;
  difficulty: Difficulty;
  source: string;
  question: string;
  correct: string;
  distractors: [string, string, string];
  explanation: string;
};

const CSF = "https://doi.org/10.6028/NIST.CSWP.29";
const IDENTITY = "https://pages.nist.gov/800-63-4/sp800-63b.html";
const CISA = "https://www.cisa.gov/secure-our-world";
const CPG = "https://www.cisa.gov/cybersecurity-performance-goals";
const OWASP = "https://owasp.org/Top10/";
const TLS = "https://www.rfc-editor.org/rfc/rfc8446";
const IR = "https://doi.org/10.6028/NIST.SP.800-61r3";
const ZERO_TRUST = "https://doi.org/10.6028/NIST.SP.800-207";
const NIST_CONTROLS = "https://doi.org/10.6028/NIST.SP.800-53r5";
const NIST_GLOSSARY = "https://doi.org/10.6028/NIST.IR.7298r3";
const KEY_MANAGEMENT = "https://doi.org/10.6028/NIST.SP.800-57pt1r5";
const MEDIA_SANITIZATION = "https://doi.org/10.6028/NIST.SP.800-88r2";
const PATCH_MANAGEMENT = "https://doi.org/10.6028/NIST.SP.800-40r4";
const CONFIGURATION = "https://doi.org/10.6028/NIST.SP.800-70r5";
const CONTINGENCY = "https://doi.org/10.6028/NIST.SP.800-34r1";
const TLS_IDENTITY = "https://www.rfc-editor.org/rfc/rfc9525";
const OWASP_ACCESS = "https://owasp.org/Top10/2025/A01_2025-Broken_Access_Control/";
const OWASP_CONFIG = "https://owasp.org/Top10/2025/A02_2025-Security_Misconfiguration/";
const OWASP_SUPPLY_CHAIN = "https://owasp.org/Top10/2025/A03_2025-Software_Supply_Chain_Failures/";
const OWASP_INJECTION = "https://owasp.org/Top10/2025/A05_2025-Injection/";
const OWASP_EXCEPTIONS = "https://owasp.org/Top10/2025/A10_2025-Mishandling_of_Exceptional_Conditions/";
const RISK_MANAGEMENT = "https://doi.org/10.6028/NIST.SP.800-39";
const SECURITY_CATEGORIZATION = "https://doi.org/10.6028/NIST.SP.800-60v1r1";
const HASH_STANDARD = "https://doi.org/10.6028/NIST.FIPS.180-4";
const AWARENESS_TRAINING = "https://doi.org/10.6028/NIST.SP.800-50r1";
const RANSOMWARE = "https://www.cisa.gov/stopransomware/ransomware-guide";

const d = (
  topic: string,
  topicSlug: string,
  objectiveCode: string,
  objective: string,
  difficulty: Difficulty,
  source: string,
  question: string,
  correct: string,
  distractors: [string, string, string],
  explanation: string,
): Draft => ({ topic, topicSlug, objectiveCode, objective, difficulty, source, question, correct, distractors, explanation });

const drafts: Draft[] = [
  d("Security principles and risk governance", "risk-governance", "CSF-RG-01", "Distinguish confidentiality, integrity, and availability", "easy", CSF, "A payroll file is readable only by authorized staff. Which security objective is primarily being met?", "Confidentiality", ["Availability", "Non-repudiation", "Integrity"], "Confidentiality limits information access and disclosure to authorized people and systems."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-02", "Distinguish confidentiality, integrity, and availability", "easy", CSF, "A monitoring system detects that an account number was altered after a report was approved. Which security property was violated?", "Integrity", ["Availability", "Confidentiality", "Redundancy"], "Integrity concerns protection against unauthorized modification or destruction of information."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-03", "Distinguish confidentiality, integrity, and availability", "easy", CSF, "A hospital keeps a critical application usable during a server failure. Which security objective does this most directly support?", "Availability", ["Confidentiality", "Attribution", "Data minimization"], "Availability means authorized users can access information and services when needed."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-04", "Apply least privilege", "easy", NIST_CONTROLS, "A new support analyst only needs to reset customer passwords. Which access decision best follows least privilege?", "Grant only the password-reset permission", ["Make the analyst a domain administrator", "Give the analyst every support-team permission", "Share a senior analyst's account"], "Least privilege grants only the permissions required for assigned duties."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-05", "Relate threats, vulnerabilities, likelihood, and impact", "medium", NIST_GLOSSARY, "A public server has a known exploitable flaw, but no patch has been applied. In risk terminology, what is the flaw?", "A vulnerability", ["A threat actor", "A business impact", "A security policy"], "A vulnerability is a weakness that a threat can exploit; the attacker or event is the threat."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-06", "Select proportionate risk treatment", "medium", RISK_MANAGEMENT, "A team stops collecting an optional sensitive field so the associated exposure can no longer occur. Which risk response is this?", "Avoid the risk", ["Accept the risk unchanged", "Transfer the financial impact", "Mitigate the likelihood"], "Removing the activity that creates the risk is risk avoidance."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-07", "Use NIST CSF 2.0 functions", "easy", CSF, "Which function was added as a distinct top-level function in NIST Cybersecurity Framework 2.0?", "Govern", ["Audit", "Prevent", "Assure"], "CSF 2.0 has six functions: Govern, Identify, Protect, Detect, Respond, and Recover."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-08", "Use NIST CSF 2.0 functions", "medium", CSF, "A company inventories systems and prioritizes them by business criticality. Which NIST CSF 2.0 function most directly covers this work?", "Identify", ["Respond to incidents", "Recover operations", "Protect existing assets"], "Identify covers understanding assets and current cybersecurity risks so they can be prioritized."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-09", "Use NIST CSF 2.0 profiles", "hard", CSF, "A security team compares its present outcomes with desired outcomes to plan improvements. Which CSF 2.0 mechanism best supports that comparison?", "Current and Target Organizational Profiles", ["CSF Implementation Examples alone", "A single CSF Implementation Tier", "The Informative References catalog"], "CSF Organizational Profiles describe current and target cybersecurity outcomes and help identify gaps."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-10", "Distinguish preventive, detective, and corrective controls", "medium", NIST_CONTROLS, "Which control is primarily detective?", "An alert on repeated failed sign-ins", ["A firewall rule that blocks an unused port", "A restored copy of a damaged database", "A policy requiring manager approval"], "The alert identifies potentially adverse activity; it does not itself prevent or repair the event."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-11", "Apply separation of duties", "medium", NIST_CONTROLS, "Which process best applies separation of duties to supplier payments?", "One employee creates the supplier and another approves payment", ["One employee creates and releases the payment after self-review", "Two employees perform the work through one shared finance account", "One employee approves payment and later reviews their own audit trail"], "Separating creation and approval reduces the chance that one person can complete and conceal fraud."),
  d("Security principles and risk governance", "risk-governance", "CSF-RG-12", "Prioritize controls by risk", "hard", CSF, "Two weaknesses are found. One is easy to exploit on an internet-facing payment system; the other is difficult to exploit on an isolated test device. What should drive remediation priority?", "Likelihood and business impact together", ["The scanner's severity label without business context", "The order in which the findings were discovered", "The remediation effort without considering exposure"], "Risk-based prioritization considers both the chance of exploitation and the resulting impact in context."),

  d("Identity and access management", "identity-access", "CSF-IAM-01", "Recognize authentication factors", "easy", IDENTITY, "A user signs in with a password and a registered hardware security key. Why is this multi-factor authentication?", "It combines knowledge and possession factors", ["It combines two knowledge factors", "It repeats one possession factor", "It uses two versions of the same password"], "A password is something known, while the registered security key is something possessed; they are distinct factors."),
  d("Identity and access management", "identity-access", "CSF-IAM-02", "Recognize authentication factors", "easy", IDENTITY, "A user enters a password and then a second PIN. How many authentication factor types are being used?", "One", ["Two", "Three", "Four"], "A password and PIN are both knowledge factors, so using both is not multi-factor authentication."),
  d("Identity and access management", "identity-access", "CSF-IAM-03", "Select phishing-resistant authentication", "medium", IDENTITY, "Which sign-in option is designed to resist a fake site relaying a user's authenticator output?", "A FIDO2/WebAuthn security key bound to the site", ["A password sent through a separate email message", "A security question answered on the requesting site", "A hardware-token code manually typed into the site"], "WebAuthn can bind authentication to the verifier name; manually entered OTPs are not phishing-resistant under NIST SP 800-63B-4."),
  d("Identity and access management", "identity-access", "CSF-IAM-04", "Apply account lifecycle controls", "easy", CSF, "An employee leaves the company. What is the most important immediate identity action?", "Disable or remove the employee's access", ["Rename the account but preserve its sessions", "Archive the mailbox but retain application access", "Transfer files while keeping the account enabled"], "Prompt deprovisioning prevents a former user from continuing to access organizational resources."),
  d("Identity and access management", "identity-access", "CSF-IAM-05", "Apply role-based access", "medium", NIST_CONTROLS, "A hospital assigns permissions to nurses based on the nursing job function rather than one permission at a time. What access model is being used?", "Role-based access control", ["Attribute-based access control", "Discretionary access control", "Network-based access control"], "RBAC groups permissions into roles associated with job functions."),
  d("Identity and access management", "identity-access", "CSF-IAM-06", "Use secure password practices", "easy", IDENTITY, "Which user practice best limits password-stuffing risk across websites?", "Use a unique password for each account", ["Reuse one complex password everywhere", "Add the website name to the same base password", "Share passwords with a trusted coworker"], "Unique passwords prevent a password exposed by one service from directly unlocking other services."),
  d("Identity and access management", "identity-access", "CSF-IAM-07", "Use secure password practices", "medium", IDENTITY, "Under NIST SP 800-63B-4, what should trigger a forced password change?", "Evidence that the password is compromised", ["A fixed 90-day interval regardless of evidence", "Every successful login from a known device", "A change in the user's job title alone"], "The guideline rejects arbitrary periodic changes and requires a change when compromise is evident."),
  d("Identity and access management", "identity-access", "CSF-IAM-08", "Protect privileged accounts", "medium", NIST_CONTROLS, "Which practice best protects an administrator who also reads email?", "Use a separate privileged account only for administrative tasks", ["Use one privileged account for administration, browsing, and email", "Use the privileged account but disable its activity logging", "Use a shared privileged account for every operations team member"], "Separating routine and privileged work reduces exposure and makes privileged actions easier to attribute."),
  d("Identity and access management", "identity-access", "CSF-IAM-09", "Apply zero-trust access principles", "medium", ZERO_TRUST, "In a zero-trust architecture, what should happen simply because a request originates on the office network?", "It should still be evaluated against access policy", ["It should be trusted while its source has an internal IP address", "It should bypass authentication until the device leaves the office", "It should receive elevated permissions for the current session"], "Zero trust does not grant implicit trust based only on network location; access decisions evaluate identity, resource, and context."),
  d("Identity and access management", "identity-access", "CSF-IAM-10", "Manage service credentials safely", "hard", OWASP_CONFIG, "An application needs a database credential. Which approach is safest?", "Use a dedicated least-privilege service identity and managed secret storage", ["Use a shared administrator credential stored in the deployment script", "Use a developer's personal account stored in an environment file", "Use a long-lived team password embedded in the application image"], "A dedicated identity limits permissions and supports rotation, revocation, and attribution without exposing a human credential."),
  d("Identity and access management", "identity-access", "CSF-IAM-11", "Respond to lost authenticators", "medium", IDENTITY, "A user reports that a registered hardware authenticator was stolen. What should the service provide?", "A way to invalidate that authenticator promptly", ["A downloadable public copy of the authenticator's private key", "Permanent fallback access without any authentication", "A recovery flow that leaves the stolen authenticator active"], "NIST requires a mechanism to invalidate a physical authenticator when loss, theft, or compromise is suspected."),
  d("Identity and access management", "identity-access", "CSF-IAM-12", "Apply authentication throttling", "hard", IDENTITY, "Which verifier control most directly slows online password guessing without locking every account after one mistake?", "Rate-limit repeated failed authentication attempts", ["Require a password-composition change after every failed attempt", "Delay only successful authentication responses", "Discard failed-attempt audit events after each login"], "Throttling limits the rate of online guesses while a measured policy avoids trivial denial of service."),

  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-01", "Recognize phishing indicators", "easy", CISA, "An unexpected message claims an invoice is overdue and urges immediate login through a shortened link. What is the safest first action?", "Use a known contact method to verify the request", ["Open the link and inspect it after signing in", "Reply with the account password", "Forward it to every coworker"], "Urgency and an unexpected login link are phishing indicators; verify through a trusted channel before acting."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-02", "Handle suspicious attachments", "easy", CISA, "A sender you do not know emails a macro-enabled document and asks you to enable content. What should you do?", "Do not open it; report it through the approved channel", ["Enable macros so the message can be checked", "Upload it to a public forum", "Rename the file and run it"], "Unexpected active-content attachments can deliver malware; reporting preserves the evidence for security review."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-03", "Distinguish social-engineering methods", "easy", NIST_GLOSSARY, "An attacker calls the help desk pretending to be an executive and demands an urgent password reset. What attack technique is this?", "Pretexting", ["Port scanning", "Data deduplication", "Load balancing"], "Pretexting uses a fabricated identity or story to persuade someone to disclose information or perform an action."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-04", "Recognize ransomware behavior", "easy", RANSOMWARE, "Users suddenly cannot open shared files, and each folder contains a demand for payment. What incident is most likely?", "Ransomware", ["A normal software update", "A successful backup test", "A DNS cache refresh"], "Ransomware commonly encrypts or otherwise denies access to data and presents an extortion demand."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-05", "Contain suspected malware safely", "medium", IR, "A workstation begins contacting known malicious domains. What should an analyst do first under an approved incident procedure?", "Isolate the workstation while preserving relevant evidence", ["Delete all logs immediately", "Announce that every system is clean", "Connect it to more network segments"], "Isolation can limit spread and command-and-control traffic while evidence preservation supports analysis."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-06", "Distinguish malware types", "medium", NIST_GLOSSARY, "Malicious code disguises itself as a useful installer and depends on the user running it. Which description fits best?", "A Trojan", ["A firewall", "A digital certificate", "A network route"], "A Trojan presents itself as legitimate or desirable software to persuade a user to execute it."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-07", "Recognize credential attacks", "medium", IDENTITY, "An attacker tries username-password pairs leaked from one website against many other websites. What is this called?", "Credential stuffing", ["Password salting", "Certificate pinning", "Network segmentation"], "Credential stuffing exploits password reuse by testing known credential pairs on other services."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-08", "Protect against removable-media risk", "easy", AWARENESS_TRAINING, "You find an unlabelled USB drive in a car park. What is the safest response?", "Give it to the designated security or IT team without connecting it", ["Connect it to a work computer to identify the owner", "Copy its files to a shared drive", "Take it home and disable antivirus"], "Unknown removable media may contain malicious content; trained staff can handle it under controlled procedures."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-09", "Recognize business email compromise", "medium", CISA, "A finance employee receives a lookalike-domain email asking to change a supplier's bank details. What control is most effective before payment?", "Verify the change using a known independent contact channel", ["Trust the display name", "Reply only to the same email", "Skip the normal approval workflow"], "Independent verification breaks the attacker's control of the email conversation and helps prevent fraudulent redirection."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-10", "Respond to accidental disclosure", "medium", IR, "An employee sends a confidential file to the wrong external recipient. What should the employee do first?", "Report the disclosure promptly through the incident channel", ["Delete the sent-message record and say nothing", "Wait to see whether the recipient complains", "Post the same file publicly"], "Prompt reporting lets responders assess scope, attempt containment, and meet applicable notification duties."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-11", "Recognize denial-of-service symptoms", "hard", NIST_GLOSSARY, "A public service is overwhelmed by traffic from many unrelated compromised devices. Which attack best fits?", "A distributed denial-of-service attack", ["A distributed password-spraying campaign", "A large vulnerability-scanning campaign", "A certificate-transparency monitoring query"], "A distributed denial-of-service attack uses many sources to exhaust a service or its supporting resources."),
  d("Threats and secure user behavior", "threats-behavior", "CSF-THR-12", "Use updates as a protective behavior", "easy", CISA, "Why should users install verified security updates promptly?", "Updates often correct flaws attackers could exploit", ["Updates guarantee that social engineering cannot succeed", "Updates replace the need for tested recovery copies", "Updates replace every need for layered access controls"], "Security updates reduce exposure by correcting known weaknesses, although they do not replace other controls."),

  d("Network and application security", "network-app-security", "CSF-NAS-01", "Understand TLS protections", "easy", TLS, "What does TLS primarily protect while application data travels between endpoints?", "Confidentiality and integrity in transit", ["Availability during every outage", "Authorization to every application feature", "Permanent deletion of server logs"], "TLS encrypts transmitted data and detects modification; authentication is also provided for the server side of the channel."),
  d("Network and application security", "network-app-security", "CSF-NAS-02", "Use certificate validation safely", "medium", TLS_IDENTITY, "A browser warns that a banking site's certificate does not match the hostname. What should the user do?", "Stop and verify the site's address through a trusted route", ["Ignore the warning and enter credentials", "Disable certificate checks permanently", "Send the password by email instead"], "A hostname mismatch can indicate misconfiguration or interception; bypassing validation removes an important authentication check."),
  d("Network and application security", "network-app-security", "CSF-NAS-03", "Apply network segmentation", "medium", CPG, "Why place public web servers in a segment separated from internal finance systems?", "To limit paths an attacker can use after compromising a web server", ["To make all internal systems public", "To eliminate the need for patching", "To guarantee that the web server cannot fail"], "Segmentation constrains reachability and can reduce lateral movement and incident impact."),
  d("Network and application security", "network-app-security", "CSF-NAS-04", "Apply firewall allowlisting", "easy", CPG, "A database should accept connections only from two application servers. Which firewall policy best supports this?", "Allow those sources to the required database port and deny other inbound sources", ["Allow every source to every port", "Block the two application servers", "Expose the database directly to the internet"], "A narrowly scoped allow rule enforces least privilege at the network layer."),
  d("Network and application security", "network-app-security", "CSF-NAS-05", "Recognize broken access control", "medium", OWASP_ACCESS, "A user changes `/orders/501` to `/orders/502` and sees another customer's order without an authorization check. Which OWASP Top 10:2025 category best fits?", "Broken Access Control", ["Cryptographic Failures", "Software Supply Chain Failures", "Mishandling of Exceptional Conditions"], "The application failed to enforce whether the requester could access the selected object."),
  d("Network and application security", "network-app-security", "CSF-NAS-06", "Prevent injection", "medium", OWASP_INJECTION, "Which coding practice most directly reduces SQL injection risk?", "Use parameterized queries with untrusted values bound as data", ["Build SQL by concatenating raw user input", "Hide database errors only", "Rename the database tables weekly"], "Parameterized queries keep untrusted values separate from the SQL command structure."),
  d("Network and application security", "network-app-security", "CSF-NAS-07", "Recognize security misconfiguration", "medium", OWASP_CONFIG, "A production admin console still uses the vendor's default password. Which OWASP Top 10:2025 category most directly applies?", "Security Misconfiguration", ["Broken Access Control only", "Injection", "Insecure Design only"], "Leaving default credentials enabled is an insecure configuration that exposes privileged functionality."),
  d("Network and application security", "network-app-security", "CSF-NAS-08", "Use secure application error handling", "hard", OWASP_EXCEPTIONS, "An application fails open and approves a transaction when its authorization service times out. Which OWASP Top 10:2025 category most directly highlights this behavior?", "Mishandling of Exceptional Conditions", ["Software Supply Chain Failures", "Cryptographic Failures", "Security Logging and Alerting Failures"], "The application handled an exceptional dependency failure unsafely; a sensitive authorization path should fail securely."),

  d("Data protection and cryptography", "data-crypto", "CSF-DPC-01", "Distinguish encryption and hashing", "easy", IDENTITY, "Which operation is intended to be one-way and is commonly used when verifying stored passwords?", "Cryptographic hashing", ["Reversible symmetric encryption", "Base64 text encoding", "Lossless file compression"], "Password verification uses a salted password-hashing scheme rather than storing a reversible plaintext password."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-02", "Use password storage controls", "medium", IDENTITY, "How should a verifier store centrally checked passwords?", "As salted hashes using a suitable password-hashing scheme", ["In a readable spreadsheet", "Encrypted with a key stored beside the data and no other controls", "As the first four characters only"], "NIST requires salted, hashed password storage and recommends a costly password-hashing approach that impedes offline guessing."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-03", "Protect encryption keys", "medium", KEY_MANAGEMENT, "Encrypted customer data and its decryption key are stored in the same publicly readable folder. What is the main problem?", "Anyone who obtains both can decrypt the data", ["Encryption makes the data unavailable to its owner forever", "The key automatically becomes a hash", "The folder can no longer be backed up"], "Encryption only protects confidentiality while the decryption key remains appropriately controlled."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-04", "Apply data minimization", "easy", NIST_CONTROLS, "A registration form collects passport numbers even though the service never uses them. What is the best security improvement?", "Stop collecting the unnecessary passport numbers", ["Publish the numbers for transparency", "Keep them indefinitely just in case", "Email them to every administrator"], "Data minimization reduces the amount of sensitive information that can be exposed or misused."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-05", "Classify information", "medium", SECURITY_CATEGORIZATION, "Why classify information as public, internal, confidential, or similarly defined levels?", "To apply handling controls appropriate to sensitivity and impact", ["To guarantee all files have equal value", "To replace access control", "To remove the need for retention rules"], "Classification connects information sensitivity to access, storage, transmission, retention, and disposal requirements."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-06", "Protect data throughout its lifecycle", "medium", MEDIA_SANITIZATION, "A failed drive contained sensitive data and is leaving the organization. Which action is most appropriate?", "Use an approved sanitization or destruction method", ["Place it in ordinary electronic waste without sanitization", "Rename the drive in the asset register and release it", "Delete its desktop shortcut before transferring the media"], "Approved sanitization or physical destruction helps prevent recovery of data from retired media."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-07", "Use integrity verification", "hard", HASH_STANDARD, "A vendor publishes a software image and a trusted cryptographic digest. What can a matching digest establish?", "The downloaded bytes match the bytes represented by that digest", ["The software has no vulnerabilities", "The publisher's identity without any trusted binding", "The software will run on every device"], "A matching digest checks content integrity, but authenticity requires a trusted way to bind the expected digest or signature to the publisher."),
  d("Data protection and cryptography", "data-crypto", "CSF-DPC-08", "Differentiate transport and storage protections", "easy", TLS, "A company uses TLS for uploads but stores uploaded files unencrypted on a shared server. What does TLS protect?", "The files while they are transmitted", ["The stored files after the TLS connection ends", "Every backup copy forever", "The permissions on the shared server"], "TLS protects data in transit; separate controls are required for data at rest."),

  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-01", "Prioritize vulnerability remediation", "medium", CPG, "A critical actively exploited flaw affects an internet-facing gateway. What is the best remediation priority?", "Treat it as urgent based on exploitation and exposure", ["Wait for the routine cycle because all findings share one deadline", "Prioritize an isolated low-impact issue because it is older", "Defer it because automated scanners sometimes produce false positives"], "Known exploitation, exposure, and business impact justify urgent risk-based remediation."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-02", "Use secure configuration baselines", "medium", CONFIGURATION, "Why compare servers regularly with an approved secure configuration baseline?", "To detect unauthorized or risky configuration drift", ["To force identical settings on systems with different roles", "To replace the need for an accurate asset inventory", "To eliminate the need to control administrator accounts"], "Baseline comparison reveals deviations from reviewed settings that may introduce risk."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-03", "Reduce attack surface", "easy", OWASP_CONFIG, "A server runs an unused remote-management service exposed to the internet. What is the safest change?", "Disable or remove the unused service", ["Keep it enabled but publish new credentials", "Move it to a different public-facing port", "Keep it exposed but turn off its activity logging"], "Removing unnecessary services reduces reachable functionality that could contain exploitable weaknesses."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-04", "Test changes before production rollout", "medium", PATCH_MANAGEMENT, "Why test a security patch on representative systems before broad deployment when time permits?", "To find compatibility problems while preserving a controlled rollout", ["To prove no future vulnerability will exist", "To avoid documenting the change", "To replace backups permanently"], "Controlled testing reduces operational risk while the deployment plan still addresses security urgency."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-05", "Handle unsupported software", "medium", CPG, "A business-critical operating system no longer receives security fixes. What is the best long-term response?", "Migrate to a supported platform using a risk-managed plan", ["Continue operating it indefinitely behind the existing firewall", "Assume endpoint antivirus can replace operating-system fixes", "Hide its version information while expanding network access"], "Unsupported software accumulates uncorrected weaknesses; compensating controls may be temporary, but migration addresses the root exposure."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-06", "Manage software supply-chain risk", "hard", OWASP_SUPPLY_CHAIN, "A build downloads dependencies by a mutable name without integrity verification. Which improvement best reduces supply-chain risk?", "Pin reviewed versions and verify dependency integrity", ["Allow any newer package to replace the build silently", "Disable the dependency inventory", "Store build logs only on developer laptops"], "Pinning and integrity verification reduce unexpected substitution; inventory and controlled updates support ongoing review."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-07", "Validate vulnerability scan findings", "hard", PATCH_MANAGEMENT, "A scanner reports a severe issue on a service that asset owners say is disabled. What should the analyst do next?", "Validate reachability and affected-version evidence before disposition", ["Mark it fixed without checking", "Publish the finding with customer data", "Delete the asset from inventory"], "Validation distinguishes true exposure, compensating controls, and false positives while keeping the decision auditable."),
  d("Vulnerability and configuration management", "vulnerability-config", "CSF-VCM-08", "Manage exceptions", "medium", CSF, "A patch cannot be applied before a critical business event. What makes a temporary exception defensible?", "Documented risk ownership, compensating controls, expiry, and follow-up", ["An unwritten promise with no expiry", "Disabling monitoring until the event ends", "Keeping the exception secret from the risk owner"], "A bounded, owned exception records the residual risk and ensures the decision is revisited."),

  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-01", "Use security logs", "easy", CPG, "Which log field most helps connect a privileged configuration change to a person?", "An authenticated actor identifier", ["The monitor's screen size", "The office paint color", "The printer paper type"], "An actor identity, together with time and action details, supports attribution and investigation."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-02", "Protect log integrity", "medium", CPG, "Why send important security logs to access-controlled central storage?", "To make attacker tampering and local loss harder", ["To guarantee that every generated alert is a true positive", "To avoid defining retention and access policies for each source", "To allow endpoint users to correct central log records"], "Central, restricted storage preserves evidence when a monitored endpoint is compromised or unavailable."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-03", "Create actionable alerts", "medium", CPG, "A critical log source stops sending events. What should monitoring do?", "Alert on the loss of the log source", ["Assume silence means the monitored environment is safe", "Delete earlier alerts from the same telemetry source", "Continue without recording the resulting detection gap"], "A silent sensor creates a detection gap, so loss of telemetry should itself be detectable."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-04", "Triage alerts", "medium", IR, "What is the best first triage question for an alert about impossible travel?", "Do the identity, timestamps, locations, and known user activity support compromise?", ["Can the alert be closed because travel is possible in general?", "Should all evidence be deleted?", "Can the user's manager's password be shared?"], "Triage validates the signal in context before escalation, containment, or closure."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-05", "Preserve incident evidence", "hard", IR, "Why record who collected a forensic image, when, and each transfer of custody?", "To demonstrate the evidence's handling and integrity", ["To make the source device process evidence more quickly", "To replace technical analysis of the collected evidence", "To guarantee the image alone identifies the attacker"], "Chain-of-custody records help show how evidence was obtained, controlled, and transferred."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-06", "Contain incidents proportionately", "medium", IR, "A compromised user account is actively sending phishing messages. Which containment action is most direct?", "Disable the account and revoke active sessions under the response plan", ["Increase the account's privileges", "Delete all mail-system logs", "Wait until the next annual audit"], "Disabling the identity and revoking sessions interrupts the attacker's current use while investigation continues."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-07", "Communicate incidents safely", "medium", IR, "Who should make external statements during a major incident?", "Authorized communicators following the incident communication plan", ["Any employee using personal social media", "The attacker", "Whoever first sees an alert"], "Coordinated, authorized communication reduces misinformation and supports legal, regulatory, customer, and operational needs."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-08", "Distinguish event and incident", "easy", IR, "A successful administrator login during an approved maintenance window is recorded. What is it by default?", "A security-relevant event that needs context", ["Automatically a confirmed incident", "Proof that logging failed", "A mandatory data breach"], "An event is an observable occurrence; analysis and context determine whether it is an incident."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-09", "Eradicate root causes", "medium", IR, "After isolating malware, why identify the initial access path before returning systems to service?", "To correct the weakness and reduce reinfection risk", ["To avoid restoring business operations", "To justify deleting all backups", "To make monitoring unnecessary"], "Removing malware without fixing the exploited path can allow the same compromise to recur."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-10", "Learn from incidents", "easy", IR, "What is the main purpose of a post-incident review?", "Improve controls, plans, and response based on evidence", ["Assign blame without changing anything", "Erase the incident timeline", "Declare that similar incidents are impossible"], "Lessons learned convert incident evidence into prioritized improvements and updated procedures."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-11", "Prioritize incident handling", "hard", IR, "Which incident should generally receive the higher initial priority?", "Active compromise of a critical service with continuing data loss", ["A blocked scan with no affected asset", "A resolved low-risk policy typo", "A test alert generated during an announced exercise"], "Priority reflects current impact, criticality, scope, and urgency rather than alert count alone."),
  d("Monitoring and incident response", "monitoring-response", "CSF-MIR-12", "Coordinate incident response with risk management", "hard", IR, "According to NIST SP 800-61 Rev. 3, how should incident response relate to cybersecurity risk management?", "It should be integrated across the CSF 2.0 functions", ["It should begin only after every preventive control fails", "It should be isolated from governance and recovery", "It should be limited to forensic imaging"], "Revision 3 frames incident response as part of cybersecurity risk management across Govern, Identify, Protect, Detect, Respond, and Recover."),

  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-01", "Use resilient backups", "easy", CPG, "Which backup design most improves recovery from ransomware that can reach the production network?", "A tested backup copy isolated from normal production access", ["A single writable copy mounted on every server", "A shortcut to the original files", "A backup whose restore process is unknown"], "Isolation limits an attacker's ability to alter the recovery copy, and restore testing demonstrates usability."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-02", "Test restoration", "medium", CONTINGENCY, "A backup job reports success every night. What additional evidence is needed before relying on it?", "A successful restore test that meets recovery needs", ["A larger backup icon", "A promise that the media is new", "A count of unrelated help-desk tickets"], "A completed backup does not prove that data is intact, usable, or restorable within required time."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-03", "Distinguish recovery objectives", "medium", CONTINGENCY, "Which measure states the maximum acceptable amount of data loss expressed as time?", "Recovery point objective", ["Recovery time objective", "Mean time to restore service", "Maximum password lifetime"], "RPO describes how far back in time recovery data may be; RTO describes how quickly service should be restored."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-04", "Distinguish recovery objectives", "medium", CONTINGENCY, "Which measure states the target time to restore a service after disruption?", "Recovery time objective", ["Recovery point objective", "Password entropy", "Packet time to live"], "RTO is the target duration for restoring a service to an acceptable level after disruption."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-05", "Use business continuity planning", "easy", CONTINGENCY, "A customer portal is unavailable, but staff use a documented manual order process. What capability does this demonstrate?", "Business continuity", ["Credential stuffing", "Data exfiltration", "Privilege escalation"], "Business continuity keeps essential work operating through alternate processes while normal services are restored."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-06", "Validate recovery securely", "hard", IR, "Before reconnecting rebuilt systems after an intrusion, what should the recovery team verify?", "The root cause is addressed and restored systems meet security requirements", ["All security logs have been erased", "Every account has administrator access", "The original vulnerable configuration is restored unchanged"], "Secure recovery checks that the attacker path is corrected and the restored environment is trustworthy enough to resume operations."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-07", "Plan dependencies", "medium", CONTINGENCY, "A recovery plan restores an application but omits its identity provider and DNS dependencies. What is the main risk?", "The application may remain unusable despite being restored", ["The application will automatically become public domain", "The backups will turn into logs", "The recovery time objective will become a password"], "Recovery planning must include the services and suppliers on which the business service depends."),
  d("Resilience and recovery", "resilience-recovery", "CSF-RRC-08", "Improve recovery plans", "easy", IR, "What should happen to recovery procedures after an exercise reveals outdated contact details?", "Update the procedures and retest the affected steps", ["Keep the known error for consistency", "Cancel all future exercises", "Remove ownership from the plan"], "Exercises are useful when their findings lead to owned improvements and validation."),
];

if (drafts.length !== 80) throw new Error(`Expected 80 questions, found ${drafts.length}`);

// Deterministically balance and shuffle answer positions inside every blueprint topic.
// Each topic count is divisible by four, so this also produces twenty of each bank-wide.
const positions: number[] = [];
let state = 0x5ec0_2026;
const random = () => {
  state ^= state << 13;
  state ^= state >>> 17;
  state ^= state << 5;
  return (state >>> 0) / 0x1_0000_0000;
};
for (let start = 0; start < drafts.length;) {
  let end = start + 1;
  while (end < drafts.length && drafts[end].topic === drafts[start].topic) end += 1;
  const topicPositions = Array.from({ length: end - start }, (_, index) => index % 4);
  for (let index = topicPositions.length - 1; index > 0; index -= 1) {
    const swap = Math.floor(random() * (index + 1));
    [topicPositions[index], topicPositions[swap]] = [topicPositions[swap], topicPositions[index]];
  }
  positions.push(...topicPositions);
  start = end;
}

const items = drafts.map((draft, index) => {
  const correctOption = positions[index];
  const options = [...draft.distractors];
  options.splice(correctOption, 0, draft.correct);
  return {
    schemaVersion: 1,
    sourceRecordId: `csf-v1-${String(index + 1).padStart(3, "0")}`,
    language: "en",
    question: draft.question,
    format: "mcq_single",
    options,
    answer: { kind: "single_choice", correctOption },
    explanation: draft.explanation,
    subject: "Cybersecurity",
    topic: draft.topic,
    syllabus: "Octamy Cybersecurity Foundations OCT-CSF-2026.1",
    exam: "Cybersecurity Foundations",
    examYear: null,
    objective: `${draft.objectiveCode}: ${draft.objective}`,
    difficulty: draft.difficulty,
    maxPoints: 1,
    negativeMarks: 0,
    timeLimitSec: 75,
    tags: ["cybersecurity", draft.topicSlug, draft.objectiveCode.toLowerCase(), "original", "version-1"],
    provenance: {
      sourceLocator: draft.source,
      questionOrigin: "original",
      answerEvidence: draft.explanation,
      explanationOrigin: "original",
    },
    metadata: {
      bankSlug: "cybersecurity-foundations-pool-v1",
      assessmentSlugs: ["cybersecurity-foundations"],
      topicSlug: draft.topicSlug,
      syllabusVersion: "OCT-CSF-2026.1",
      objectiveCode: draft.objectiveCode,
      releaseEvidenceVersion: "1.0",
      authoringMethod: "AI-assisted original draft",
      answerVerificationMethod: "Mapped to cited primary guidance; independent item review required",
      reviewerStatus: "pending",
      distractorReviewStatus: "pending",
    },
  };
});

const outputDirectory = path.resolve("content/career-question-banks/cybersecurity-foundations-v1");
await mkdir(outputDirectory, { recursive: true });
await writeFile(
  path.join(outputDirectory, "questions.jsonl"),
  `${items.map((item) => JSON.stringify(item)).join("\n")}\n`,
  "utf8",
);

process.stdout.write(`${JSON.stringify({ outputDirectory, questions: items.length }, null, 2)}\n`);
